CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) UNIQUE NOT NULL
);

CREATE TABLE articles (
    article_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(200) NOT NULL,
    date DATE DEFAULT SYSDATE,
    text CLOB,
    user_id NUMBER REFERENCES users(user_id)
);

CREATE TABLE comments (
    comment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    url VARCHAR2(200),
    article_id NUMBER REFERENCES articles(article_id),
    user_id NUMBER REFERENCES users(user_id)
);

CREATE TABLE tags (
    tag_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) UNIQUE NOT NULL,
    url VARCHAR2(200)
);

CREATE TABLE categories (
    category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) UNIQUE NOT NULL,
    url VARCHAR2(200)
);

CREATE TABLE article_tags (
    article_id NUMBER REFERENCES articles(article_id),
    tag_id NUMBER REFERENCES tags(tag_id),
    PRIMARY KEY(article_id, tag_id)
);

CREATE TABLE article_categories (
    article_id NUMBER REFERENCES articles(article_id),
    category_id NUMBER REFERENCES categories(category_id),
    PRIMARY KEY(article_id, category_id)
);
